spring:
  h2:
    console:
      path: /h2
    enabled: true
  jpa:
    defer-datasource-inicialization: true
  datasource:
    url: jdbc:h2:mem:cobranca
    driverClassName: org.h2.Driver
    username: admin
server:
  port: 9047
logging:
  config:
    src/main/resources/logback-test.xml
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJha2FkaW9uLWVycC1zdmMtYmNrLXRlc3QiLCJuYW1lIjoiQWthZGlvbiBFUlAgdGVzdCBlbnZpcm9ubWVudCIsImlhdCI6MTY5MDEwOTg1NH0.hqDnSClAZUVgq_iuCDXc4ZI9ySXigVNZN4XwDQfy1IE
  expiration: 604800000

# ASAAS
URL_ASAAS: https://sandbox.asaas.com
TOKEN_ASAAS: $aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNDkyNDA6OiRhYWNoXzBlZGM0MDUwLTBhYWMtNGM1Ni04MThhLTE0YzlmYmQ2MmZjYQ==
TOKEN_WEBHOOK_ASAAS: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2ViaG9vayBBU0FBUyBhbWJpZW50ZSBkZSB0ZXN0ZXMiLCJpYXQiOjEyNDY0Mzk4NzF9.ikyCMBdpWkls-HQ8likkoJP8WchrsfIusRyTVi4PVpQ

log_context: TEST